experiment:
  # paths used in experiment_runner.py
  paths:
    ros2_ws: "~/ros2_ws"
    results_dir: "~/ros2_ws/results"
    rosbags_dir: "~/ros2_ws/rosbag_files"

  experiments:
    experiment1:
      # Map - map name for experiment(tune_rosbags and evaluation_rosbags)
      map: map1
      # Tune - enable tuning algorithms parameters
      tune: false
      # Tune rosbag- rosbag on which algorithms params will be tuned
      tune_rosbag: tune1
      # Evaluation - enable algorithms evaluation
      evaluation: true
      # Evaluation runs - number of runs for evaluating the algorithm on one rosbag
      evaluation_runs: 10
      # Evaluation rosbags - rosbags on which algorithms performace will be tested
      # evaluation rosbags 1 - rosbags without any changes in the map
      # evaluation rosnags 2 - rosbags with changes in the map
      evaluation_rosbags_1: [square1, eight1]
      evaluation_rosbags_2: [square12, eight12]
      # evaluation_rosbags_2: []
      # Initial pose values used to evaluation of the algorithms convergence
      initial_pose:
        x: [-3.0, -4.0, -5.0]
        # x: [-4.0, -5.0]
        # x: 0.0
        y: 0.0
        # yaw: 0.0
        # yaw: [30.0, 45.0, 60.0, 90.0]
        yaw: 0.0
        z: 0.0

    experiment2:
      # Map - map name for experiment(tune_rosbags and evaluation_rosbags)
      map: map2
      # Tune - enable tuning algorithms parameters
      tune: false
      # Tune rosbag- rosbag on which algorithms params will be tuned
      tune_rosbag: tune2
      # Evaluation - enable algorithms evaluation
      evaluation: true
      # Evaluation runs - number of runs for evaluating the algorithm on one rosbag
      evaluation_runs: 10
      # Evaluation rosbags - rosbags on which algorithms performace will be tested
      # evaluation rosbags 1 - rosbags without any changes in the map
      # evaluation rosnags 2 - rosbags with changes in the map
      evaluation_rosbags_1: [square2, eight22]
      evaluation_rosbags_2: [square22, eight2]
      # Initial pose values used to evaluation of the algorithms convergence
      initial_pose:
        x: [-1.0, -2.0, -3.0, -4.0, -5.0]
        # x: 0.0
        y: 0.0
        # yaw: 0.0
        yaw: 120.0
        # yaw: 0.0
        # yaw: [30.0, 45.0, 60.0, 90.0]
        z: 0.0

mocap:
  # dx, dy, dz [m] are distances between mocap base point and robor base point (base_link)
  # dtheta [rad] is the oritnation difference between both coordinate systems
  # It is used to make a transform between mocap coordinate system and robot coordinate system
  dx: 0.0
  dy: 0.0
  dz: 0.0
  dtheta: 0.0

rosbag_generator:
  ros__parameters:
    timer_period: 0.1
    # available paths are in ~/localization_benchmarking/paths_def.py file
    # available paths: square, eight, all (all paths one after each other)
    path_name: "eight"
    rosbags_dir: "~/ros2_ws/rosbag_files"
    rosbag_name: eight22
    path_execution: true

algorithms:

  amcl:
    amcl:
      ros__parameters:
        alpha1: 0.1
        alpha2: 0.1
        alpha3: 0.1
        alpha4: 0.1
        alpha5: 0.1
        base_frame_id: "base_footprint"
        service_introspection_mode: "disabled"
        beam_skip_distance: 0.5
        beam_skip_error_threshold: 0.9
        beam_skip_threshold: 0.3
        do_beamskip: false
        global_frame_id: "map"
        lambda_short: [0.05, 0.1]
        laser_likelihood_max_dist: 5.0
        laser_max_range: 100.0
        laser_min_range: -1.0
        laser_model_type: "likelihood_field"
        max_beams: 50
        max_particles: 1125
        min_particles: 1000
        odom_frame_id: "odom"
        pf_err: [0.03, 0.05, 0.1]
        pf_z: [0.9, 0.99]
        recovery_alpha_fast: [0.0, 0.1]
        recovery_alpha_slow: [0.0, 0.001]
        resample_interval: 1
        robot_model_type: "nav2_amcl::DifferentialMotionModel"
        save_pose_rate: 10.0
        sigma_hit: 0.2
        tf_broadcast: true
        transform_tolerance: 1.0
        update_min_a: 0.05
        update_min_d: [0.025, 0.05]
        z_hit: [0.5, 0.8, 0.9]
        z_max: 0.05
        z_rand: 0.1
        z_short: 0.05
        scan_topic: /tb6/scan
        map_topic: map
        set_initial_pose: false
        always_reset_initial_pose: false
        first_map_only: false
        initial_pose:
          x: 0.0
          y: 0.0
          z: 0.0
          yaw: 0.0

    map_server:
      ros__parameters:
        use_sim_time: True
        # Overridden in launch by the "map" launch configuration or provided default value.
        # To use in yaml, remove the default "map" value in the tb3_simulation_launch.py file & provide full path to map below.
        yaml_filename: ""

# -----------pfStandardProposal------------
  mrpt:
    /**:
      ros__parameters:
        gnss_samples_num_sigmas: 6.0
        gui_camera_follow_robot: true
        gui_enable: true
        initial_particles_per_m2: 1
        initial_pose:
          mean:
            pitch: 0.0
            roll: 0.0
            x: 0.0
            y: 0.0
            yaw: 0.0
            z: 0.0
          std_pitch: 0.0
          std_roll: 0.0
          std_x: 0.4 # deviation at start[m]
          std_y: 0.4
          std_yaw: 0.1 # 1 sigma uncertainty [radians]
          std_z: 0.0
        kld_options:
          KLD_binSize_PHI: 0.17
          KLD_binSize_XY: 0.25
          KLD_delta: 0.05
          KLD_epsilon: 0.05
          KLD_maxSampleSize: 5000
          KLD_minSampleSize: 100
          KLD_minSamplesPerBin: 1
        motion_model_2d:
          gaussianModel:
            a1: 0.01 # [m/m] translation noise when translation
            a2: 0.01 # [m/rad] translation noise when rotation
            a3: 0.01 # [deg/m] rotation noise when translation
            a4: 0.005 # [deg/deg] rotation noise when rotation
            minStdPHI: 0.01 # [deg] minimal rotational deviation
            minStdXY: 0.01  # [m] minimal translational deviation
          modelSelection: mmGaussian
          thrunModel:
            additional_std_XY: 0.02
            additional_std_phi: 0.05
            alfa1_rot_rot: 0.05
            alfa2_rot_trans: 0.05
            alfa3_trans_trans: 0.05
            alfa4_trans_rot: 0.05
        motion_model_3d:
          modelSelection: mmGaussian
        motion_model_no_odom_2d: # Even if there is no movement, the particles move a little – to maintain variety.
          gaussianModel:
            minStdPHI: 0.1 # [deg] minimal deviation
            minStdXY: 0.01 # [m] minimal deviation
          modelSelection: mmGaussian
        motion_model_no_odom_3d:
          modelSelection: mmGaussian
        override_likelihood_gridmaps:
          LF_decimation: [1, 2] # use every n beam - 1 means all eams are considered
          LF_maxCorrsDistance: [0.1, 0.15, 0.2] # Maximum distance of a scan point from an obstacle in the map to still be considered a match.
          LF_maxRange: 81.0
          LF_stdHit: [0.1, 0.2] # tells us how “wide” the distribution of the probability of hitting an obstacle is.
          LF_zHit: [0.85, 0.9, 0.95]  # trust for hitting objects
          LF_zRandom: [0.15, 0.1, 0.05] # probabilities of random measurements
          likelihoodMethod: lmLikelihoodField_Thrun
        override_likelihood_point_maps:
          decimation: 1
          max_corr_distance: 0.2
          sigma_dist: 0.1
        pf_options:
          BETA: [0.1, 0.3, 0.5, 0.7] # modifies the effect of particle weights during resampling. Too large → degeneracy, too small → slow convergence
          adaptiveSampleSize: false
          PF_algorithm: pfStandardProposal 
          max_loglikelihood_dyn_range: 10
          pfAuxFilterOptimal_MLE: false
          pfAuxFilterOptimal_MaximumSearchSamples: 250
          pfAuxFilterStandard_FirstStageWeightsMonteCarlo: false
          powFactor: 1.0
          resamplingMethod: prMultinomial
        rate_hz: 10.0
        relocalization_icp_sigma: 0.2 #excpeted pose error [m] - too high a too large setting will cause bad matches to be accepted, while a too small setting may ignore good matches.
        relocalization_initial_divisions_phi: 5 #grid resolution at relocalization - higher then more hyphotesis of pose and more accurate but computational more expensive
        relocalization_initial_divisions_xy: 10 #grid resolution at relocalization
        relocalization_minimum_icp_quality: 0.8 # minimal acceptable quality of ICP - ratio of paired points/ all points. Below that the hyphotesis is rejected
        relocalization_resolution_phi: 1.0 # [deg] angle step when relocalization
        relocalization_resolution_xy: 0.5 #[m] transational step when relocalization
        relocalize_num_sigmas: 1.0 # the number of standard deviations around which particles are scattered in the event of relocalization. The larger the value, the more widely the particles are scattered.
        relocalization_min_sample_copies_per_candidate: 25
        samples_drawn_from_gnss: 20
        use_se3_pf: false


# # # # # -----------pfAuxiliaryPFStandard------------
#   mrpt:
#     /**:
#       ros__parameters:
#         gnss_samples_num_sigmas: 6.0
#         gui_camera_follow_robot: true
#         gui_enable: true
#         initial_particles_per_m2: 1
#         initial_pose:
#           mean:
#             pitch: 0.0
#             roll: 0.0
#             x: 0.0
#             y: 0.0
#             yaw: 0.0
#             z: 0.0
#           std_pitch: 0.0
#           std_roll: 0.0
#           std_x: 0.4 # deviation at start[m]
#           std_y: 0.4
#           std_yaw: 0.1 # 1 sigma uncertainty [radians]
#           std_z: 0.0
#         kld_options:
#           KLD_binSize_PHI: 0.17
#           KLD_binSize_XY: 0.25
#           KLD_delta: 0.05
#           KLD_epsilon: 0.05
#           KLD_maxSampleSize: 5000
#           KLD_minSampleSize: 100
#           KLD_minSamplesPerBin: 1
#         motion_model_2d:
#           gaussianModel:
#             a1: 0.01 # [m/m] translation noise when translation
#             a2: 0.01 # [m/rad] translation noise when rotation
#             a3: 0.01 # [deg/m] rotation noise when translation
#             a4: 0.005 # [deg/deg] rotation noise when rotation
#             minStdPHI: 0.01 # [deg] minimal rotational deviation
#             minStdXY: 0.01  # [m] minimal translational deviation
#           modelSelection: mmGaussian
#           thrunModel:
#             additional_std_XY: 0.02
#             additional_std_phi: 0.05
#             alfa1_rot_rot: 0.05
#             alfa2_rot_trans: 0.05
#             alfa3_trans_trans: 0.05
#             alfa4_trans_rot: 0.05
#         motion_model_3d:
#           modelSelection: mmGaussian
#         motion_model_no_odom_2d: # Even if there is no movement, the particles move a little – to maintain variety.
#           gaussianModel:
#             minStdPHI: 0.01 # [deg] minimal deviation
#             minStdXY: 0.01 # [m] minimal deviation
#           modelSelection: mmGaussian
#         motion_model_no_odom_3d:
#           modelSelection: mmGaussian
#         override_likelihood_gridmaps:
#           LF_decimation: [1, 2] # use every n beam - 1 means all eams are considered
#           LF_maxCorrsDistance: [0.1, 0.15, 0.2] # Maximum distance of a scan point from an obstacle in the map to still be considered a match.
#           LF_maxRange: 81.0
#           LF_stdHit: [0.1, 0.2] # tells us how “wide” the distribution of the probability of hitting an obstacle is.
#           LF_zHit: [0.85, 0.9, 0.95]  # trust for hitting objects
#           LF_zRandom: [0.15, 0.1, 0.05] # probabilities of random measurements
#           likelihoodMethod: lmLikelihoodField_Thrun
#         override_likelihood_point_maps:
#           decimation: 2
#           max_corr_distance: 0.2
#           sigma_dist: 0.1
#         pf_options:
#           BETA: [0.1, 0.3, 0.5, 0.7] # modifies the effect of particle weights during resampling. Too large → degeneracy, too small → slow convergence
#           adaptiveSampleSize: false
#           PF_algorithm: pfAuxiliaryPFStandard 
#           max_loglikelihood_dyn_range: 10
#           pfAuxFilterOptimal_MLE: false
#           pfAuxFilterOptimal_MaximumSearchSamples: 250
#           pfAuxFilterStandard_FirstStageWeightsMonteCarlo: false
#           powFactor: 1.0
#           resamplingMethod: prMultinomial
#         rate_hz: 10.0
#         relocalization_icp_sigma: 0.2 #excpeted pose error [m] - too high a too large setting will cause bad matches to be accepted, while a too small setting may ignore good matches.
#         relocalization_initial_divisions_phi: 5 #grid resolution at relocalization - higher then more hyphotesis of pose and more accurate but computational more expensive
#         relocalization_initial_divisions_xy: 10 #grid resolution at relocalization
#         relocalization_minimum_icp_quality: 0.8 # minimal acceptable quality of ICP - ratio of paired points/ all points. Below that the hyphotesis is rejected
#         relocalization_resolution_phi: 1.0 # [deg] angle step when relocalization
#         relocalization_resolution_xy: 0.5 #[m] transational step when relocalization
#         relocalize_num_sigmas: 1.0 # the number of standard deviations around which particles are scattered in the event of relocalization. The larger the value, the more widely the particles are scattered.
#         relocalization_min_sample_copies_per_candidate: 25
#         samples_drawn_from_gnss: 20
#         use_se3_pf: false
