amcl:
  ros__parameters:
    alpha1: 0.1
    alpha2: 0.1
    alpha3: 0.1
    alpha4: 0.1
    alpha5: 0.1
    always_reset_initial_pose: false
    base_frame_id: base_footprint
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    first_map_only: false
    global_frame_id: map
    initial_pose:
      x: 0.0
      y: 0.0
      yaw: 120.0
      z: 0.0
    lambda_short: 0.1
    laser_likelihood_max_dist: 5.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: likelihood_field
    map_topic: map
    max_beams: 50
    max_particles: 1000
    min_particles: 1000
    odom_frame_id: odom
    pf_err: 0.03
    pf_z: 0.9
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.001
    resample_interval: 1
    robot_model_type: nav2_amcl::DifferentialMotionModel
    save_pose_rate: 10.0
    scan_topic: /tb6/scan
    service_introspection_mode: disabled
    set_initial_pose: false
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.05
    update_min_d: 0.025
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.1
    z_short: 0.05
map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: ''
